---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true
  when:
    - ansible_pkg_mgr == "apt"

- name: Update yum cache
  ansible.builtin.yum:
    update_cache: yes
  become: true
  when:
    - ansible_pkg_mgr == "yum"

- name: Update dnf cache
  ansible.builtin.dnf:
    update_cache: yes
  become: true
  when:
    - ansible_pkg_mgr == "dnf"
