---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 600
  when:
    - ansible_pkg_mgr == "apt"

- name: Update yum cache
  yum:
    update_cache: yes
  when:
    - ansible_pkg_mgr == "yum"
